// lib/models/motivetxt.dart

class MotiveTxt {
  static const List<String> rdmTxt = [
    "Başarı, sabır ve azimle gelir.",
    "Hayallerine inan, çünkü onlar seni geleceğine taşır.",
    "Bugün yaptığın şey yarının temelini oluşturur.",
    "Başarı, asla pes etmeyenlerindir.",
    "Her düşüş bir ders, her kalkış bir zaferdir.",
    "Kendi hikayenin kahramanı ol.",
    "Başarı, hazırlık ve fırsatın kesiştiği yerdedir.",
    "Büyük başarılar, küçük ama tutarlı adımlarla gelir.",
    "Yol uzun olabilir, ama her adım seni zirveye taşır.",
    "Düşüncelerine dikkat et, çünkü onlar senin geleceğindir.",
    "Küçük bir adım bile büyük değişiklikler yaratabilir.",
    "Hata yapmaktan korkma, çünkü onlar başarının anahtarıdır.",
    "Düşüncelerini değiştir, hayatın değişsin.",
    "Her sabah yeni bir başlangıçtır.",
    "En karanlık anların arkasında ışık vardır.",
    "Bir fikrin varsa, ona inan ve peşinden git.",
    "Hayallerini gerçekleştirmek için bugün bir adım at.",
    "Korkuların seni durdurmasına izin verme.",
    "Zorluklar, başarının habercisidir.",
    "Hayatta ne kadar ileri gideceğin, cesaretine bağlıdır.",
    "Pozitif bir zihin, pozitif bir hayat yaratır.",
    "Hayatta en önemli şey, kendi şansını yaratmaktır.",
    "Her yeni gün, yeni bir fırsat getirir.",
    "Gülümsemek, en güzel enerjidir.",
    "Hayat, sen ne düşünüyorsan onu sana geri verir.",
    "Kendine inan; bu, başarının yarısıdır.",
    "Zorluklar seni daha güçlü yapar.",
    "Her düşüş, kalkmak için bir fırsattır.",
    "Küçük mutluluklar, büyük mutlulukları getirir.",
    "Hayatın her anı bir hediyedir.",
    "Yapamazsın diyenlere inat, yap!",
    "Hayal etmekten asla vazgeçme.",
    "Sen başarırsan, herkes sustuğunda kazanırsın.",
    "Hedefine odaklan, gerisi kendiliğinden gelir.",
    "Engeller, başarı yolunda sadece bir merdivendir.",
    "Kıçıktüm ama şimdi buradayım; her şey mümkün.",
    "Kendi potansiyelini keşfetmeden asla pes etme.",
    "Hiçbir zafer, savaşmadan kazanılmaz.",
    "Sen yeter ki iste; imkansız diye bir şey yoktur.",
    "İnanırsan, yaparsın!",
  ];
}
